[package]
name = "nxdk-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
nxdk-sys = { path = "nxdk-sys" }
libc = "0.2.169"
bitflags = "2.9.1"
embedded-io = "0.6.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
members = [
    "nxdk-sys"
]
