/* automatically generated by rust-bindgen 0.69.5 */

pub const WHITE: u32 = 16777215;
pub const BLACK: u32 = 0;
pub const WHITE_16BPP: u32 = 65535;
pub const BLACK_16BPP: u32 = 0;
pub const WHITE_15BPP: u32 = 32767;
pub const BLACK_15BPP: u32 = 0;
extern "C" {
    #[doc = " Prints a message to whatever debug facilities might\n be available."]
    pub fn debugPrint(format: *const libc::c_char, ...);
}
extern "C" {
    pub fn debugPrintNum(i: libc::c_int);
}
extern "C" {
    pub fn debugPrintBinary(num: libc::c_int);
}
extern "C" {
    pub fn debugPrintHex(buffer: *const libc::c_char, length: libc::c_int);
}
extern "C" {
    pub fn debugClearScreen();
}
extern "C" {
    pub fn debugAdvanceScreen();
}
extern "C" {
    pub fn debugMoveCursor(x: libc::c_int, y: libc::c_int);
}
extern "C" {
    pub fn debugResetCursor();
}
