/* automatically generated by rust-bindgen 0.69.5 */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
extern "C" {
    #[doc = " Retrieves the path to the currently running XBE as an NT-style path\n (e.g. like \\Device\\CdRom0\\default.xbe).\n @param path Address of the buffer (with at least MAX_PATH length) where the path will be stored"]
    pub fn nxGetCurrentXbeNtPath(path: *mut libc::c_char);
}
