/* automatically generated by rust-bindgen 0.64.0 */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
extern "C" {
    pub fn nxIsDriveMounted(driveLetter: libc::c_char) -> bool;
}
extern "C" {
    pub fn nxMountDrive(driveLetter: libc::c_char, path: *const libc::c_char) -> bool;
}
extern "C" {
    pub fn nxUnmountDrive(driveLetter: libc::c_char) -> bool;
}
