/* automatically generated by rust-bindgen 0.69.5 */

pub type XAudioCallback = ::core::option::Option<
    unsafe extern "C" fn(pac97Device: *mut libc::c_void, data: *mut libc::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AC97_DESCRIPTOR {
    pub bufferStartAddress: libc::c_uint,
    pub bufferLengthInSamples: libc::c_ushort,
    pub bufferControl: libc::c_ushort,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AC97_DEVICE {
    pub pcmSpdifDescriptor: [AC97_DESCRIPTOR; 32usize],
    pub pcmOutDescriptor: [AC97_DESCRIPTOR; 32usize],
    pub mmio: *mut libc::c_uint,
    pub nextDescriptor: libc::c_uchar,
    pub callback: XAudioCallback,
    pub callbackData: *mut libc::c_void,
    pub sampleSizeInBits: libc::c_int,
    pub numChannels: libc::c_int,
}
extern "C" {
    pub fn XAudioInit(
        sampleSizeInBits: libc::c_int,
        numChannels: libc::c_int,
        callback: XAudioCallback,
        data: *mut libc::c_void,
    );
}
extern "C" {
    pub fn XAudioPlay();
}
extern "C" {
    pub fn XAudioPause();
}
extern "C" {
    pub fn XAudioProvideSamples(
        buffer: *mut libc::c_uchar,
        bufferLength: libc::c_ushort,
        isFinal: libc::c_int,
    );
}
